// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// const SUPABASE_URL = "https://dimypdbdnmuwuanlirze.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpbXlwZGJkbm11d3VhbmxpcnplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDI1NzgsImV4cCI6MjA2NzkxODU3OH0.KxvnKlPEdH09H3g39MAZjqrnZzUznX4qYutqb6xpX7w";

const SUPABASE_URL = "https://ghfiyvfdhugnesqjotwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoZml5dmZkaHVnbmVzcWpvdHdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjM3MzcsImV4cCI6MjA2OTAzOTczN30.9-2zZ1tP0VOJFZ4hqltkVdhRQBbTSJWRiIK4aDjYuyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});